### ISSUE TITLE
Batch size in ResourceTagInsertion.java (lesson 04)

### ISSUE THREAD

**Issue by Dimanaux** [SZabirov/javalab_db#1]
Проблема [тут](https://github.com/SZabirov/javalab_db/blob/master/lesson04/src/main/java/ru/itis/javalab/db/lesson04/ResourceTagInsertion.java).

На каждой десятитысячной итерации цикла выполняется `statement.executeBatch()` и `connection.commit()`, это приводит к выполнению всех накопленных запросов прямо в БД.

При этом предыдущие запросы остаются в batch, что приводит к выполнению некоторых запросов многократно.

**Comment by SZabirov** [comment]
1) Да, поведение в данном случае такое же, как если бы мы использовали autoCommit (о чем было сказано во время занятия)
2) Насчет предыдущих запросов в batch - не понял. Согласно документации (пункт 14.1.2 https://download.oracle.com/otndocs/jcp/jdbc-4_2-mrel2-spec/index.html) `executeBatch()` очищает batch

**Comment by Dimanaux** [comment]
> 1. Да, поведение в данном случае такое же, как если бы мы использовали autoCommit (о чем было сказано во время занятия)
> 2. Насчет предыдущих запросов в batch - не понял. Согласно документации (пункт 14.1.2 https://download.oracle.com/otndocs/jcp/jdbc-4_2-mrel2-spec/index.html) `executeBatch()` очищает batch

Большое спасибо за ответ!
